@baseUrl = http://localhost:5122
@productId = 2779ee47-10b0-4bd7-8342-404006aa1392

###
GET {{baseUrl}}/api/products/text

###
GET {{baseUrl}}/api/products/json

###
GET {{baseUrl}}/api/products/i-result/{{productId}}

###
GET {{baseUrl}}/api/products/type-result/{{productId}}