### 1- Build Stage :
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS Build
WORKDIR /source
COPY OrderServiceApi/*.csproj OrderServiceApi/
RUN dotnet restore OrderServiceApi/OrderServiceApi.csproj
COPY OrderServiceApi/. ./OrderServiceApi
WORKDIR /source/OrderServiceApi
RUN dotnet publish -c Release -o /app --no-restore

### Final stage (final image)
FROM mcr.microsoft.com/dotnet/aspnet:10.0 As Final
WORKDIR /app
COPY --from=Build /app ./
ENTRYPOINT [ "dotnet","OrderServiceApi.dll" ]

