// <auto-generated />
using System;
using AuthenticationWithJWT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthenticationWithJWT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725120813_addRefreshTokens")]
    partial class addRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthenticationWithJWT.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Permissions")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Roles")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BirthDate = new DateOnly(1995, 1, 1),
                            Email = "supermanager@test.com",
                            FirstName = "Super",
                            LastName = "Manager",
                            PasswordHash = "AQAAAAIAAYagAAAAEMgowEOmfyX1Fg2pVWG9Y3g9EmziM9VtE4sFqvfIMrhOiy/RLoXtfnaNNHd1FSFSTg==",
                            Permissions = "[\"project:create\",\"project:read\",\"project:update\",\"project:delete\",\"project:assign_member\",\"project:manage_budget\",\"task:create\",\"task:read\",\"task:update\",\"task:delete\",\"task:assign_user\",\"task:update_status\",\"task:comment\"]",
                            Roles = "[\"supermanager\"]"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BirthDate = new DateOnly(1997, 1, 1),
                            Email = "manager@test.com",
                            FirstName = "Project",
                            LastName = "Manager",
                            PasswordHash = "AQAAAAIAAYagAAAAENKcW6STYSBPHp/ZOs3E/hxeH1r06H3kZ0Eltq1NnY9oZ96w5UGAT0z6Fy8QNFqHpA==",
                            Permissions = "[\"project:create\",\"project:read\",\"project:update\",\"project:delete\",\"project:assign_member\",\"project:manage_budget\"]",
                            Roles = "[\"manager\"]"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BirthDate = new DateOnly(2000, 1, 1),
                            Email = "employee@test.com",
                            FirstName = "Employee",
                            LastName = "User",
                            PasswordHash = "AQAAAAIAAYagAAAAEEN611uY7ftj3llpfZo2d8zCn9kyo0Zxqxb/AswL3uWQYFNjFegvCupnkaGUjU4NJw==",
                            Permissions = "[\"task:create\",\"task:read\",\"task:update\",\"task:delete\",\"task:assign_user\",\"task:update_status\",\"task:comment\"]",
                            Roles = "[\"employee\"]"
                        });
                });

            modelBuilder.Entity("AuthenticationWithJWT.Models.AppUser", b =>
                {
                    b.OwnsMany("AuthenticationWithJWT.Models.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<Guid>("AppUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AppUserId", "Id");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("AppUserId");
                        });

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
