@baseUrl = http://localhost:5160

@ProductId = 2779ee47-10b0-4bd7-8342-404006aa1392
###
OPTIONS {{baseUrl}}/api/products

###
Head {{baseUrl}}/api/products/{{ProductId}}

###
GET {{baseUrl}}/api/products/{{ProductId}}?includeReviews=true

###
GET {{baseUrl}}/api/products?page=1&size=20

###
POST {{baseUrl}}/api/products
Content-Type: application/json

{
    "name":"Product 5",
    "price":12.00
}

###
PUT  {{baseUrl}}/api/products/{{ProductId}}
Content-Type: application/json

{
    "name":"Product 3",
    "price":12.00
}

###
PATCH {{baseUrl}}/api/products/{{ProductId}}
Content-Type: application/json-patch+json

[
    {
        "op":"replace",
        "path":"/price",
        "value":45.00
    },
    {
        "op":"replace",
        "path":"/name",
        "value":"name after patch"
    }
]

###
DELETE {{baseUrl}}/api/products/{{ProductId}}

###
Post {{baseUrl}}/api/products/process

@processId = 5cacc212-68c0-4825-b29e-f5e4582d3dbe
###
GET {{baseUrl}}/api/products/status/{{processId}}

###
GET {{baseUrl}}/api/products/in-memory-report

###
GET {{baseUrl}}/api/products/physical-report

###
GET {{baseUrl}}/api/products/old-products